### PR TITLE
Render info

### PR DESCRIPTION
**Pull request by tinotenda6**

### CODE REVIEW

**Comment by zhaonian** [comment]
Could you do a `git pull origin main` so that we can see the changes based off the latest main branch please?

**Comment by aanddrea** [comment]
[image: Screen Shot 2021-04-12 at 4.58.18 PM.png]
hello this is what I get, I'm not sure how to fix it!

**Comment by zhaonian** [comment]
@aanddrea for some reason I could not see your screenshot. Let's try to figure this out in the meeting :)

**Comment by aanddrea** [comment]
Ok sounds good! Thank you so much.

**Comment by NolShep** [comment]
Yea like zhaonian said, make sure to pull our latest branch and work of that so there aren't conflicts (I learned that the hard way last week 😂)

**Review by zhaonian — APPROVED** [review]
LGTM. Thanks! Could you do a "squash and merge" plz?

**Pull request merged**
