### PR TITLE
navbar and bootstrap cdn

### PR DESCRIPTION
**Pull request by NolShep**

### CODE REVIEW

**Comment by NolShep** [comment]
^navigation bar and bootstrap cdn

**Comment by zhaonian** [comment]
Hi Nolan, are you done with this PR? Could you request reviews when it's ready for review please so that we know you are done? :)

**Comment by NolShep** [comment]
Sorry, I forgot to do that... oops! Just pinged you

**Review by zhaonian — APPROVED** [review]
Ah ok LGTM! thanks!

**Pull request merged**
